# Generated by Django 6.0.2 on 2026-03-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_group_to_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='survey_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
