# Generated by Django 6.0.2 on 2026-03-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_survey_index_to_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='survey_index',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
